#!/usr/bin/env bash
# display DNS information for domains and sub-domains


print_subdomain ()
{
	if [ "$2" == www ]; then
		dig "$2.$1" | grep -e ^www | awk ' {print "The subdomain " substr($1, 1, 3) " is a " $4 " record and points to " $5}'
	elif [ "$2" == lb-01 ]; then
		dig "$2.$1" | grep -e ^lb-01 | awk ' {print "The subdomain " substr($1, 1, 5) " is a " $4 " record and points to " $5}'
	elif [ "$2" == web-01 ]; then
		dig "$2.$1" | grep -e ^web-01 | awk ' {print "The subdomain " substr($1, 1, 6) " is a " $4 " record and points to " $5}'
	elif [ "$2" == web-01 ]; then
		dig "$2.$1" | grep -e ^web-02 | awk ' {print "The subdomain " substr($1, 1, 6) " is a " $4 " record and points to " $5}'
	fi
}

print_domain ()
{
       	if [ "$subdomain" == www ]; then
               	dig "$subdomain.$1" | grep -e ^www | awk ' {print "The subdomain " substr($1, 1, 3) " is a " $4 " record and points to " $5}'
	elif [ "$subdomain" == lb-01 ]; then
               	dig "$subdomain.$1" | grep -e ^lb-01 | awk ' {print "The subdomain " substr($1, 1, 5) " is a " $4 " record and points to " $5}'
        elif [ "$subdomain" == web-01 ]; then
                dig "$subdomain.$1" | grep -e ^web-01 | awk ' {print "The subdomain " substr($1, 1, 6) " is a " $4 " record and points to " $5}'
        elif [ "$subdomain" == web-02 ]; then
                dig "$subdomain.$1" | grep -e ^web-02 | awk ' {print "The subdomain " substr($1, 1, 6) " is a " $4 " record and points to " $5}'
        fi
}


if [ -z "$2" ];
then
	for subdomain in "www" "lb-01" "web-01" "web-02"
        do
        	print_domain "$1" "$subdomain"
	done
else
	print_subdomain "$1" "$2"
fi
