#!/usr/bin/env bash
# display DNS information for domains and sub-domains


dns_info () {
    if [ "$#" -eq 1 ]
    then
        dig www."$1" +noall +answer | awk '{print "The subdomain www is a " $4 " record and points to " $5}'
        dig lb-01."$1" +noall +answer| awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
        dig web-01."$1" +noall +answer | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
        dig web-02."$1" +noall +answer | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'
    elif [ "$#" -eq 2 ]
    then
        dig "$2.$1" +noall +answer | awk '{print "The subdomain '$2' is a " $4 " record and points to " $5}'
    fi
}

dns_info $1 $2



#print_subdomain ()
#{
#	if [ "$2" == www ]; then
#		dig "$2.$1" +noall +answer | awk ' {print "The subdomain " substr($1, 1, 3) " is a " $4 " record and points to " $5}'
#	elif [ "$2" == lb-01 ]; then
#		dig "$2.$1" +noall +answer | awk ' {print "The subdomain " substr($1, 1, 5) " is a " $4 " record and points to " $5}'
#	else
#		dig "$2.$1" +noall +answer | awk ' {print "The subdomain " substr($1, 1, 6) " is a " $4 " record and points to " $5}'
#	fi
#}
#
#print_domain ()
#{
#      	if [ "$subdomain" == www ]; then
#              	dig "$subdomain.$1" +noall +answer | awk ' {print "The subdomain " substr($1, 1, 3) " is a " $4 " record and points to " $5}'
#	elif [ "$subdomain" == lb-01 ]; then
#              	dig "$subdomain.$1" +noall +answer | awk ' {print "The subdomain " substr($1, 1, 5) " is a " $4 " record and points to " $5}'
#        elif [ "$subdomain" == web-01 ]; then
#                dig "$subdomain.$1" +noall +answer | awk ' {print "The subdomain " substr($1, 1, 6) " is a " $4 " record and points to " $5}'
#       elif [ "$subdomain" == web-02 ]; then
#               dig "$subdomain.$1" +noall +answer | awk ' {print "The subdomain " substr($1, 1, 6) " is a " $4 " record and points to " $5}'
#       fi
#}
#
#
#if [ -z "$2" ];
#then
#	for subdomain in "www" "lb-01" "web-01" "web-02"
#        do
#        	print_domain "$1" "$subdomain"
#	done
#else
#	print_subdomain "$1" "$2"
#fi
