#!/usr/bin/env bash
# Install nginx on web server
# Nginx should be listening on port 80
# Querying Nginx at its root / with a GET request (requesting a page) 
# curl 54.242.177.175 returns a page containing the string Hello World!

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
