#!/usr/bin/env bash
# Install nginx on web server
# Nginx should be listening on port 80
# Configure Nginx server so that /redirect_me redirects to another page

sudo apt-get -y update
sudo apt-get -y install nginx
redirect="\\\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "48i $redirect" /etc/nginx/sites-available/default #Insert at line 48
sudo service nginx restart
