#!/usr/bin/env bash
# configure Nginx on a new server
# HTTP response contains a custom header
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/404.html
serverHeader="\\\t\n\tadd_header X-Served-By $HOSTNAME;\n\n"
redirect="\\\t\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n"
error404="error_page 404 /404.html;\n\\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n\n"
sudo sed -i "49i $redirect" /etc/nginx/sites-available/default
sudo sed -i "49i $error404" /etc/nginx/sites-available/default
sudo sed -i "49i $serverHeader" /etc/nginx/sites-available/default
sudo service nginx restart
