#!/usr/bin/env bash
# configure Nginx on a new server
# HTTP response contains a custom header
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server

sudo apt-get -y update
sudo apt-get install nginx
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
serverHeader="\\\t\n\tadd_header X-Served-By $HOSTNAME;\n\n"
sudo sed -i "49i $serverHeader" /etc/nginx/sites-available/default
sudo service nginx restart
