#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# HAproxy can be managed via an init script and use roundrobin algorithm

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install -y haproxy=2.6.\*

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

SETUP="\\\nfrontend myServer-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend myServer-backend\n\nbackend myServer-backend\n\tbalance roundrobin\n\tserver 279098-web-01 54.242.177.175:80 check\n\tserver 279098-web-02 52.91.148.117:80 check"
sudo sed -i "\$a $SETUP" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
