#!/usr/bin/env bash
# Fix bug on Nginx not listening on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
