#!/usr/bin/env bash
# Fixed bug on Nginx not listening on port 80
# service (init) must say that nginx is not running
sudo rm /etc/nginx/sites-enabled/default
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
