#!/usr/bin/env bash
# Bash script that gives information about the school file

myFile="school"
if [ -e "$myFile" ];
then
	echo "school file exists"
	if [ -f "$myFile" ];
	then
		echo "school is a regular file"
	fi
	if [ -s "$myFile" ];
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	
else
	echo "school file does not exist"
fi

