#!/usr/bin/env bash
# bash script that resolves localhost to 127.0.0.2 and facebook to 8.8.8.8

cp /etc/hosts /etc/hosts.new
sed s/127.*/127.0.0.2/ /etc/hosts.new
echo '8.8.8.8	facebook.com' >> /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
