#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user
sudo pkill apache2
sudo chmod 700 /etc/nginx/nginx.conf
chown -R nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
