#!/usr/bin/env bash
# configure SSH client
# Your SSH client configuration must be configured to use the private key ~/.ssh/school
# Your SSH client configuration must be configured to refuse to authenticate using a password

Host 54.242.177.175
     IdentityFile ~/.ssh/school
     PasswordAuthentication no
